<a href="https://colab.research.google.com/github/ananthakrishnanpta/Numpy_mini_project/blob/main/Numpy_mini_project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# Loading File to 'data_file' from google drive
from google.colab import drive
drive.mount('/content/drive')


data_file  = "/content/drive/My Drive/Colab Notebooks/Data processing/makeSenseOfCensus.csv"
file = open(data_file, 'r')



data = np.genfromtxt(data_file,delimiter = ",",skip_header=1)


print("\n Data: \n \n", data)

#Printing the type of data

print("\n Type of Data: \n\n",type(data))

#Step 2 Appending the data

new_record=[[50, 9, 4, 1, 0, 0, 40, 0]]


# Step 3

# print(census)

age = np.array(data[:,0])


max_age = age.max()

min_age = age.min()

age_mean = age.mean()

age_std = np.std(age)

#Step 4

race = np.array(data[:,2])


race_0 = race[race == 0]
race_1 = race[race == 1]
race_2 = race[race == 2]
race_3 = race[race == 3]
race_4 = race[race == 4]

len_0 = len(race_0)
len_1 = len(race_1)
len_2 = len(race_2)
len_3 = len(race_3)
len_4 = len(race_4)

print("\n Population of race 0 :- ",len_0)
print("\n Population of race 1 :- ",len_1)
print("\n Population of race 2 :- ",len_2)
print("\n Population of race 3 :- ",len_3)
print("\n Population of race 4 :- ",len_4)

minority_race = 3

#Step 5

senior_citizens = data[age > 60]

# print(senior_citizens)
working_hours_sum = senior_citizens[:,6].mean()

# print(working_hours_sum)

senior_citizens_len = len(senior_citizens)

# print(senior_citizens_len)

avg_working_hours = senior_citizens[:,6].mean()

print("\n Average working hours is:- {}. Hence the govt. policy is not followed. \n".format(avg_working_hours))

# Step 6
education_num = np.array(data[:,1])

high = data[education_num>10]
low = data[education_num<10]


income = data[:,7]

avg_pay_high = high[:,7].mean()
avg_pay_low = low[:,7].mean()
print("\n Mean avg pay for highly educated :- ",avg_pay_high)
print("\n Mean avg pay for low educated :- ",avg_pay_low)


Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

 Data: 
 
 [[39. 13.  4. ...  0. 40.  0.]
 [50. 13.  4. ...  0. 13.  0.]
 [38.  9.  4. ...  0. 40.  0.]
 ...
 [48. 13.  4. ...  0. 58.  1.]
 [40. 10.  4. ...  0. 40.  0.]
 [39. 13.  4. ...  0. 50.  1.]]

 Type of Data: 

 <class 'numpy.ndarray'>

 Population of race 0 :-  10

 Population of race 1 :-  27

 Population of race 2 :-  110

 Population of race 3 :-  6

 Population of race 4 :-  847

 Average working hours is:- 31.42622950819672. Hence the govt. policy is not followed. 


 Mean avg pay for highly educated :-  0.42813455657492355

 Mean avg pay for low educated :-  0.12723214285714285
